# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/fh/fpga/switch/switch.cache/wt [current_project]
set_property parent.project_path C:/fh/fpga/switch/switch.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/fh/fpga/switch/switch.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/fh/fpga/switch/switch.srcs/sources_1/new/constants.vhd
  C:/fh/fpga/switch/switch.srcs/sources_1/new/switch.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top switch -part xc7a100tcsg324-1


write_checkpoint -force -noxdef switch.dcp

catch { report_utilization -file switch_utilization_synth.rpt -pb switch_utilization_synth.pb }
